### ISSUE TITLE
cfd_injected.pkl can not be used successfully in AA-Smurf.py

### ISSUE THREAD

**Issue by xbingsun** [mengchillee/AutoAudit#1]
1. When I run AA-Smurf.py using cfd_injected.pkl, it has a following error.  Am I using it correctly?
![image](https://user-images.githubusercontent.com/41277992/112633602-81cd5480-8e74-11eb-99b8-5b785021ac48.png)

2. And by the way, if i want to evaluate AA-Smurf method, does the order list in the AA-Smurf.py represent the suspicious ranking of intermediate accounts?

Look forward to your reply!

**Comment by mengchillee** [comment]
Hi, thank you for asking!

1. If you are using cfd_injected.pkl, please uncomment line 99 in "AA-Smurf.py".
Because that data is an edge list not a matrix.
2. The intermediate accounts in one "Smurfing" pattern are sharing the same suspicious ranking.
There is no meaning of their orders.
